http_filters:
- name: envoy.filters.http.set_metadata
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.set_metadata.v3.Config
    metadata:
    - metadata_namespace: custom.typed
      allow_overwrite: true
      typed_value:
        "@type": type.googleapis.com/envoy.extensions.filters.http.set_metadata.v3.Config
        metadata_namespace: nested_namespace
        value:
          custom_field: "typed_value"
