version: '2'
services:

  xds-server:
    build:
      context: .
      dockerfile: Dockerfile.xds
    ports:
      - "18000:18000"
    networks:
      - envoy-network

  on-prem-envoy:
    image: debug/envoy:latest
    volumes:
      - ./on-prem-envoy-custom-resolver.yaml:/etc/on-prem-envoy.yaml
    command: envoy -c /etc/on-prem-envoy.yaml --concurrency 1 -l trace --drain-time-s 3
    ports:
      - "8080:80"
      - "9000:9000"
      - "8889:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envoy-network
    depends_on:
      - xds-server

  on-prem-service:
    image: nginxdemos/hello:plain-text
    networks:
      - envoy-network

  cloud-envoy:
    image: debug/envoy:latest
    volumes:
      - ./cloud-envoy.yaml:/etc/cloud-envoy.yaml
    command: envoy -c /etc/cloud-envoy.yaml --concurrency 1 -l trace --drain-time-s 3
    ports:
      - "8081:80"
      - "9001:9000"
      - "8888:8888"
    networks:
      - envoy-network

networks:
  envoy-network:
    driver: bridge