static_resources:
  listeners:
  - name: test_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.reverse_connection
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.reverse_connection.v3.ReverseConnectionConfig
          enabled: true
          cluster_name: test_cluster
          max_connections_per_cluster: 10
          connection_timeout_seconds: 30
          debug_logging: true

  clusters:
  - name: test_cluster
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: test_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901 